name: Renew VPN Subscription

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install requests pyyaml

    - name: Get and update subscription
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        python3 vpn_refresher.py
